'use strict';
const images=['01-property-1400','02-capital-1400','03-regulatory-1400','04-guests-1400','05-design-1365','06-procurement-1400','07-schedule-1400','08-cost-1207','09-qa-1210','10-opening-1365'];
const teasers=['Get to know the ground beneath the idea.','Give the vision a financial foundation.','Know what it takes to move forward.','Make it worth the trip.','Bring the idea into focus.','Get the right things to the right place.','Connect the plan to opening day.','Know what’s behind the numbers.','Make sure the work holds up.','Be ready for the very first guest.'];
const labels=['Yes','No','Not sure'];
const storeKey='tp-card-board-v1';
const state={answers:{},active:null,question:0};
try{const stored=JSON.parse(localStorage.getItem(storeKey)||'{}');POINTS.forEach((p,i)=>p.qs.forEach((_,q)=>{const v=stored[i+':'+q];if([0,1,2].includes(v))state.answers[i+':'+q]=v}))}catch{document.querySelector('#save-status').textContent='Progress stays in this tab.'}
const $=s=>document.querySelector(s);
function count(i){return POINTS[i].qs.filter((_,q)=>state.answers[i+':'+q]!==undefined).length}
function save(){try{localStorage.setItem(storeKey,JSON.stringify(state.answers))}catch{$('#save-status').textContent='Progress stays in this tab.'}}
function front(i){const p=POINTS[i],n=count(i);return `<img src="../../assets/points/${images[i]}.webp" alt="" ${i>3?'loading="lazy"':''}><span class="card-number">${p.n}</span><span class="flip-icon" aria-hidden="true">${n===4?'✓':'↻'}</span><div class="front-copy"><div class="teaser">${teasers[i]}</div><h2>${p.title}</h2><div class="front-bottom"><span>${n===4?'Complete · tap to review':n?`${n} of 4 answered · continue`:'4 questions · flip to explore'}</span><span class="front-dots" aria-hidden="true">${p.qs.map((_,q)=>`<i class="${state.answers[i+':'+q]!==undefined?'filled':''}"></i>`).join('')}</span></div></div>`}
function buildBoard(){$('#board').innerHTML=POINTS.map((p,i)=>`<article class="card ${count(i)===4?'complete':''}" id="card-${i}"><div class="card-inner"><button class="face front" id="front-${i}" aria-label="${p.title}: ${count(i)===4?'complete, review answers':'flip to explore four questions'}" aria-expanded="false" aria-controls="back-${i}" data-flip="${i}">${front(i)}</button><section class="face back" id="back-${i}" aria-label="${p.title} questions" inert aria-hidden="true"></section></div></article>`).join('');document.querySelectorAll('[data-flip]').forEach(b=>b.onclick=()=>openCard(Number(b.dataset.flip)));updateProgress()}
function updateProgress(){const done=POINTS.filter((_,i)=>count(i)===4).length;$('#answer-count').textContent=Object.keys(state.answers).length;$('#progress-label').textContent=`${done} of 10 cards complete`;$('#progress').value=done}
function refreshFront(i){const f=$('#front-'+i);f.innerHTML=front(i);f.setAttribute('aria-label',`${POINTS[i].title}: ${count(i)===4?'complete, review answers':'flip to explore four questions'}`);$('#card-'+i).classList.toggle('complete',count(i)===4);updateProgress()}
function closeCard(focus=true){if(state.active===null)return;const i=state.active;$('#card-'+i).classList.remove('open');$('#back-'+i).inert=true;$('#back-'+i).setAttribute('aria-hidden','true');$('#front-'+i).inert=false;$('#front-'+i).removeAttribute('aria-hidden');$('#front-'+i).setAttribute('aria-expanded','false');state.active=null;refreshFront(i);if(focus)$('#front-'+i).focus({preventScroll:true})}
function openCard(i){closeCard(false);state.active=i;const first=POINTS[i].qs.findIndex((_,q)=>state.answers[i+':'+q]===undefined);state.question=first<0?0:first;$('#card-'+i).classList.add('open');$('#front-'+i).setAttribute('aria-expanded','true');$('#front-'+i).inert=true;$('#front-'+i).setAttribute('aria-hidden','true');$('#back-'+i).inert=false;$('#back-'+i).removeAttribute('aria-hidden');renderBack();$('#question-'+i).focus({preventScroll:true})}
function renderBack(){const i=state.active,p=POINTS[i],q=state.question,a=state.answers[i+':'+q];$('#back-'+i).innerHTML=`<div class="back-top"><span class="eyebrow">${p.n} / ${p.title}</span><button class="close" data-close aria-label="Flip back to ${p.title}">×</button></div><nav class="q-nav" aria-label="${p.title} questions">${p.qs.map((_,j)=>`<button data-question="${j}" class="${j===q?'active':''} ${state.answers[i+':'+j]!==undefined?'answered':''}" aria-label="Question ${j+1}${state.answers[i+':'+j]!==undefined?', answered':''}" ${j===q?'aria-current="step"':''}>${state.answers[i+':'+j]!==undefined?'✓':j+1}</button>`).join('')}</nav><h3 class="question" id="question-${i}" tabindex="-1">${p.qs[q]}</h3><div class="answers" role="group" aria-labelledby="question-${i}">${labels.map((label,j)=>`<button class="answer ${a===j?'selected':''}" data-answer="${j}" aria-pressed="${a===j}">${label}<span aria-hidden="true">${a===j?'✓':'○'}</span></button>`).join('')}</div><div class="back-bottom"><span class="question-count">${count(i)} of 4 answered</span><button class="primary" data-next ${a===undefined?'disabled':''}>${count(i)===4?'Done · flip back ↻':'Next question →'}</button></div>`;
 const back=$('#back-'+i);back.querySelector('[data-close]').onclick=()=>closeCard();back.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{state.question=Number(b.dataset.question);renderBack();$('#question-'+i).focus({preventScroll:true})});
 back.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const val=Number(b.dataset.answer);const wasDone=count(i)===4;state.answers[i+':'+q]=val;save();refreshFront(i);renderBack();$('#back-'+i).querySelector(`[data-answer="${val}"]`).focus({preventScroll:true});if(!wasDone&&count(i)===4)$('#announcement').textContent=`${p.title} complete. Flip back to choose another card.`});
 back.querySelector('[data-next]').onclick=()=>{if(count(i)===4){closeCard();return}const remaining=p.qs.map((_,j)=>j).filter(j=>state.answers[i+':'+j]===undefined);state.question=remaining.find(j=>j>q)??remaining[0];renderBack();$('#question-'+i).focus({preventScroll:true})};
}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#notes-dialog').open)closeCard()});
$('#notes-open').onclick=()=>{const total=Object.keys(state.answers).length;$('#notes-content').innerHTML=`<p>${total} of 40 questions answered. ${total===40?'All ten cards are complete.':'You can return to any card at any time.'}</p>`+POINTS.map((p,i)=>`<details><summary>${p.title}<span>${count(i)} / 4</span></summary><ol>${p.qs.map((q,j)=>`<li>${q}<strong>${labels[state.answers[i+':'+j]]??'Not answered'}</strong></li>`).join('')}</ol></details>`).join('');$('#notes-dialog').showModal()};
$('#notes-close').onclick=()=>$('#notes-dialog').close();
$('#download').onclick=()=>{const text=['THE TEN POINT STANDARD — YOUR ANSWERS','',...POINTS.flatMap((p,i)=>[p.title,...p.qs.map((q,j)=>`${q}\n${labels[state.answers[i+':'+j]]??'Not answered'}`),''])].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ten-point-assessment-answers.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
buildBoard();
